export const quickCreateActions = [
  {
    id: "festival-post",
    title: "Festival Post",
    description: "Start from an upcoming moment",
    tone: "rose",
  },
  {
    id: "product-promotion",
    title: "Product Promotion",
    description: "Feature a product or new arrival",
    tone: "blue",
  },
  {
    id: "business-offer",
    title: "Business Offer",
    description: "Announce discounts or services",
    tone: "amber",
  },
  {
    id: "blank-design",
    title: "Blank Design",
    description: "Create a square social creative",
    tone: "emerald",
  },
];

export const discoveryTabs = [
  { id: "for-you", label: "For You", description: "Curated ideas for quick business posts" },
  { id: "festivals", label: "Festivals", description: "Events, dates, and festival-ready templates" },
  { id: "business", label: "Business", description: "Industry and service promotion templates" },
  { id: "product", label: "Product", description: "Product launches, discounts, and showcases" },
];

export const businessCategoryTargets = [
  { id: "clothes", label: "Clothes", tags: ["clothes", "fashion", "boutique", "wedding", "ethnic", "retail"] },
  { id: "restaurant", label: "Restaurant", tags: ["restaurant", "food", "menu", "delivery", "cafe"] },
  { id: "electrical", label: "Electrical", tags: ["electrical", "maintenance", "safety", "service"] },
  { id: "services", label: "Services", tags: ["service", "booking", "trust", "review"] },
  { id: "general", label: "General", tags: ["business", "offer", "product", "festival"] },
];

export const marketingEvents = [
  {
    id: "independence-day",
    dateLabel: "15 Aug",
    month: "Aug",
    name: "Independence Day",
    type: "National",
    region: "India",
    templateCount: 2,
    tags: ["festival", "national", "seasonal", "greeting"],
    visualClass: "from-orange-100 via-white to-emerald-100",
    accentClass: "bg-emerald-500",
  },
  {
    id: "ganesh-chaturthi",
    dateLabel: "27 Aug",
    month: "Aug",
    name: "Ganesh Chaturthi",
    type: "Festival",
    region: "India",
    templateCount: 1,
    tags: ["festival", "greeting", "seasonal", "ganesh"],
    visualClass: "from-amber-100 via-orange-50 to-rose-100",
    accentClass: "bg-amber-500",
  },
  {
    id: "rakhi",
    dateLabel: "29 Aug",
    month: "Aug",
    name: "Rakhi",
    type: "Festival",
    region: "India",
    templateCount: 1,
    tags: ["festival", "greeting", "seasonal", "rakhi"],
    visualClass: "from-pink-100 via-rose-50 to-amber-100",
    accentClass: "bg-rose-500",
  },
  {
    id: "diwali",
    dateLabel: "20 Oct",
    month: "Oct",
    name: "Diwali",
    type: "Festival",
    region: "India",
    templateCount: 2,
    tags: ["festival", "sale", "discount", "seasonal"],
    visualClass: "from-purple-100 via-amber-50 to-orange-100",
    accentClass: "bg-purple-500",
  },
  {
    id: "festive-sale-season",
    dateLabel: "Sep",
    month: "Sep",
    name: "Festive Sale Season",
    type: "Campaign",
    region: "Retail",
    templateCount: 6,
    tags: ["offer", "sale", "seasonal", "retail"],
    visualClass: "from-fuchsia-100 via-rose-50 to-orange-100",
    accentClass: "bg-fuchsia-500",
  },
  {
    id: "customer-service-week",
    dateLabel: "6 Oct",
    month: "Oct",
    name: "Customer Service Week",
    type: "Business",
    region: "Global",
    templateCount: 3,
    tags: ["service", "reviews", "trust", "care"],
    visualClass: "from-emerald-100 via-teal-50 to-cyan-100",
    accentClass: "bg-teal-500",
  },
];

export const discoverySections = [
  {
    id: "recommended-business",
    tab: "for-you",
    title: "Recommended for Your Business",
    subtitle: "Prioritized from your selected business category and reusable template metadata.",
    type: "template-rail",
    filters: ["Clothes", "Food", "Service", "Tips", "Offer"],
    viewAllEnabled: true,
    templateIds: [
      "fashion-premium-sale-01",
      "restaurant-food-offer-01",
      "service-business-promo-01",
      "business-discount-offer-01",
      "customer-review-trust-01",
      "product-launch-new-arrival-01",
      "festival-greeting-celebration-01",
      "fashion-wedding-offer-01",
      "quick-personalize-test-01",
    ],
  },
  {
    id: "trending-designs",
    tab: "for-you",
    title: "Trending Designs",
    subtitle: "Fast-moving designs for everyday posting.",
    type: "template-rail",
    filters: ["Trending", "Seasonal", "Fashion", "Launch"],
    viewAllEnabled: true,
    templateIds: [
      "fashion-premium-sale-01",
      "product-launch-new-arrival-01",
      "business-discount-offer-01",
      "restaurant-food-offer-01",
      "service-business-promo-01",
      "customer-review-trust-01",
      "festival-greeting-celebration-01",
      "monsoon-seasonal-offer-01",
    ],
  },
  {
    id: "quick-promotions",
    tab: "for-you",
    title: "Quick Promotions",
    subtitle: "Offer and announcement templates that are ready to customize.",
    type: "template-rail",
    filters: ["Offer", "Discount", "Booking", "Delivery"],
    viewAllEnabled: true,
    templateIds: [
      "business-discount-offer-01",
      "fashion-premium-sale-01",
      "service-promo-01",
      "restaurant-food-offer-01",
      "service-business-promo-01",
      "product-launch-new-arrival-01",
      "diwali-sale-01",
      "beauty-service-offer-01",
      "quick-personalize-test-01",
    ],
  },
  {
    id: "upcoming-festivals",
    tab: "festivals",
    title: "Upcoming Festivals",
    subtitle: "Upcoming event creatives with explicit event metadata.",
    type: "template-rail",
    filters: ["August", "October", "Greeting", "India"],
    viewAllEnabled: true,
    templateIds: [
      "festival-greeting-celebration-01",
      "independence-greeting-01",
      "festival-sept14-01",
      "festival-sept14-02",
      "festival-sept14-03",
      "festival-ganesh-01",
      "rakhi-greeting-01",
      "diwali-sale-01",
      "festive-clothing-offer-01",
      "discount-banner-01",
    ],
  },
  {
    id: "festival-offers",
    tab: "festivals",
    title: "Festival Offers",
    subtitle: "Seasonal discounts and retail campaigns.",
    type: "template-rail",
    filters: ["Sale", "Retail", "Fashion", "Food"],
    viewAllEnabled: true,
    templateIds: [
      "festival-greeting-celebration-01",
      "festival-sept14-01",
      "festival-sept14-02",
      "festival-sept14-03",
      "fashion-premium-sale-01",
      "restaurant-food-offer-01",
      "business-discount-offer-01",
      "diwali-sale-01",
      "festive-clothing-offer-01",
      "boutique-sale-01",
    ],
  },
  {
    id: "greetings",
    tab: "festivals",
    title: "Greetings",
    subtitle: "Warm brand-ready wishes with logo and business-name overlays.",
    type: "template-rail",
    filters: ["Greeting", "Brand", "Seasonal"],
    viewAllEnabled: true,
    templateIds: [
      "festival-greeting-celebration-01",
      "festival-sept14-01",
      "festival-sept14-02",
      "festival-sept14-03",
      "festival-ganesh-01",
      "independence-greeting-01",
      "rakhi-greeting-01",
      "diwali-sale-01",
      "customer-review-trust-01",
      "clinic-awareness-01",
    ],
  },
  {
    id: "business-tips",
    tab: "business",
    title: "Business Tips",
    subtitle: "Helpful posts that build trust before the sale.",
    type: "template-rail",
    filters: ["Tips", "Safety", "Care", "Maintenance"],
    viewAllEnabled: true,
    templateIds: [
      "service-business-promo-01",
      "customer-review-trust-01",
      "business-discount-offer-01",
      "info-safety-01",
      "home-maintenance-tip-01",
      "clinic-awareness-01",
      "electrical-service-promo-01",
      "service-promo-01",
      "monsoon-seasonal-offer-01",
    ],
  },
  {
    id: "customer-reviews",
    tab: "business",
    title: "Customer Reviews",
    subtitle: "Review and testimonial layouts for customer confidence.",
    type: "template-rail",
    filters: ["Review", "Trust", "Cafe", "Service"],
    viewAllEnabled: true,
    templateIds: [
      "customer-review-trust-01",
      "customer-review-01",
      "cafe-review-01",
      "restaurant-food-offer-01",
      "service-business-promo-01",
      "business-discount-offer-01",
      "clinic-awareness-01",
    ],
  },
  {
    id: "service-promotions",
    tab: "business",
    title: "Service Promotions",
    subtitle: "Bookable service creatives for local businesses.",
    type: "template-rail",
    filters: ["Service", "Booking", "Electrical", "Beauty", "Food"],
    viewAllEnabled: true,
    templateIds: [
      "service-business-promo-01",
      "business-discount-offer-01",
      "restaurant-food-offer-01",
      "service-promo-01",
      "electrical-service-promo-01",
      "beauty-service-offer-01",
      "discount-banner-01",
    ],
  },
  {
    id: "new-launch",
    tab: "product",
    title: "New Launch",
    subtitle: "Announce new products, menus, or services.",
    type: "template-rail",
    filters: ["Launch", "New Arrival", "Product"],
    viewAllEnabled: true,
    templateIds: [
      "product-launch-new-arrival-01",
      "new-launch-clean-01",
      "product-promo-01",
      "product-showcase-grid-01",
      "fashion-premium-sale-01",
      "ethnic-wear-showcase-01",
      "restaurant-food-offer-01",
      "beauty-service-offer-01",
    ],
  },
  {
    id: "sale-discount",
    tab: "product",
    title: "Sale & Discount",
    subtitle: "Promote discounts, combos, and limited-time offers.",
    type: "template-rail",
    filters: ["Sale", "Discount", "Combo", "Festive"],
    viewAllEnabled: true,
    templateIds: [
      "fashion-premium-sale-01",
      "business-discount-offer-01",
      "restaurant-food-offer-01",
      "discount-banner-01",
      "business-offer-01",
      "diwali-sale-01",
      "boutique-sale-01",
      "festive-clothing-offer-01",
      "food-delivery-post-01",
      "monsoon-seasonal-offer-01",
    ],
  },
  {
    id: "product-showcase",
    tab: "product",
    title: "Product Showcase",
    subtitle: "Image-led formats for collections, bundles, and hero products.",
    type: "template-rail",
    filters: ["Showcase", "Fashion", "Grid", "Retail"],
    viewAllEnabled: true,
    templateIds: [
      "product-launch-new-arrival-01",
      "fashion-premium-sale-01",
      "restaurant-food-offer-01",
      "product-showcase-grid-01",
      "ethnic-wear-showcase-01",
      "fashion-wedding-offer-01",
      "customer-review-01",
      "restaurant-menu-offer-01",
    ],
  },
];

export const recentDesigns = [];
