import ganeshPosterJoyfulFlyer from "../../assets/home/ganesh_chturthi/Joyful Ganesh Chaturthi Flyer (us Letter) - Made with PosterMyWall.jpg";
import ganeshPosterOrangeJoyful from "../../assets/home/ganesh_chturthi/Orange Joyful Ganesh Chaturthi Poster - Made with PosterMyWall.jpg";
import ganeshPosterRedMinimal from "../../assets/home/ganesh_chturthi/Red Modern  Minimal Ganesh Chaturthi  A4 - Made with PosterMyWall.jpg";

const ASSET_BASE = "/marketing-studio/templates";

const baseElement = {
  rotation: 0,
  opacity: 1,
  locked: false,
  editable: true,
};

const squareCanvas = { width: 1080, height: 1080, label: "1080 x 1080px" };
const landscapeCanvas = { width: 1200, height: 675, label: "1200 x 675px" };
const ganeshPosterCanvas01 = { width: 853, height: 1280, label: "853 x 1280px" };
const ganeshPosterCanvas02 = { width: 904, height: 1280, label: "904 x 1280px" };
const ganeshPosterCanvas03 = { width: 989, height: 1281, label: "989 x 1281px" };

const categoryWeights = {
  clothes: ["clothes", "fashion", "boutique", "wedding", "ethnic", "retail", "product", "offer", "festival"],
  restaurant: ["restaurant", "food", "menu", "delivery", "cafe", "offer", "review", "local"],
  electrical: ["electrical", "service", "maintenance", "safety", "tips", "home"],
  services: ["service", "promotion", "trust", "review", "maintenance", "business"],
  general: ["business", "offer", "product", "festival", "review", "tips"],
};

function createGaneshQuickPersonalizeConfig(canvas, headingDefault = "Ganesh Chaturthi Special") {
  return {
    headingDefault,
    fields: {
      logo: {
        x: Math.round(canvas.width * 0.07),
        y: Math.round(canvas.height * 0.06),
        width: Math.round(canvas.width * 0.15),
        height: Math.round(canvas.width * 0.15),
        cornerRadius: 24,
        borderColor: "#ffffff",
        borderWidth: 5,
        strokeWidth: 5,
      },
      businessName: {
        x: Math.round(canvas.width * 0.25),
        y: Math.round(canvas.height * 0.075),
        width: Math.round(canvas.width * 0.5),
        height: Math.round(canvas.height * 0.055),
        fontFamily: "Inter",
        fontSize: Math.round(canvas.width * 0.042),
        fontWeight: 900,
        fill: "#ffffff",
        align: "left",
      },
      heading: {
        x: Math.round(canvas.width * 0.1),
        y: Math.round(canvas.height * 0.78),
        width: Math.round(canvas.width * 0.8),
        height: Math.round(canvas.height * 0.11),
        fontFamily: "Georgia",
        fontSize: Math.round(canvas.width * 0.066),
        fontWeight: 700,
        fill: "#ffffff",
        align: "center",
        lineHeight: 1.05,
      },
    },
  };
}

const templateRecords = [
  {
    id: "fashion-premium-sale-01",
    title: "Premium Fashion Sale",
    category: "Fashion",
    templateType: "editable",
    format: "square-post",
    thumbnail: "fashion-premium-sale-01.svg",
    primaryImage: "fashion-premium-sale-01-photo.jpg",
    canvas: squareCanvas,
    businessCategories: ["clothes", "fashion", "boutique"],
    discoveryTabs: ["for-you", "business", "product"],
    sections: ["trending-designs", "quick-promotions", "sale-discount"],
    tags: ["fashion", "sale", "boutique", "promotion", "offer", "premium", "style"],
    assets: {
      primaryImageSource: "pexels",
      primaryImageCredit: "Eric Weise",
      primaryImageUrl: "https://www.pexels.com/photo/a-woman-in-black-dress-and-boots-sitting-on-a-couch-28133643/",
    },
    brandBindings: ["brand.businessName", "brand.phone", "brand.website", "brand.logo", "brand.primaryColor", "brand.accentColor"],
    elementsFactory: createFashionPremiumSaleElements,
  },
  {
    id: "restaurant-food-offer-01",
    title: "Restaurant Food Offer",
    category: "Food",
    templateType: "editable",
    format: "square-post",
    thumbnail: "restaurant-food-offer-01.svg",
    primaryImage: "restaurant-food-offer-01-photo.jpg",
    canvas: squareCanvas,
    businessCategories: ["restaurant", "food", "cafe"],
    discoveryTabs: ["for-you", "business", "product"],
    sections: ["recommended-business", "quick-promotions", "product-showcase", "sale-discount"],
    tags: ["restaurant", "food", "offer", "combo", "delivery", "promotion"],
    assets: {
      primaryImageSource: "pexels",
      primaryImageCredit: "Farhad Ibrahimzade",
      primaryImageUrl: "https://www.pexels.com/photo/couple-sitting-and-eating-healthy-meals-on-a-dining-table-8697540/",
    },
    brandBindings: ["brand.businessName", "brand.phone", "brand.logo", "brand.accentColor"],
    elementsFactory: createRestaurantFoodOfferElements,
  },
  {
    id: "festival-greeting-celebration-01",
    title: "Festival Greeting Celebration",
    category: "Festival",
    templateType: "editable",
    format: "square-post",
    thumbnail: "festival-greeting-celebration-01.svg",
    primaryImage: "festival-greeting-celebration-01-photo.jpg",
    canvas: squareCanvas,
    businessCategories: ["general", "clothes", "restaurant", "services"],
    discoveryTabs: ["festivals", "for-you", "business"],
    sections: ["upcoming-festivals", "greetings", "festival-offers", "trending-designs"],
    tags: ["festival", "greeting", "celebration", "diwali", "seasonal", "brand"],
    assets: {
      primaryImageSource: "pexels",
      primaryImageCredit: "Bakkaprabhu Uppar",
      primaryImageUrl: "https://www.pexels.com/photo/diwali-lamp-with-glowing-flame-on-dark-background-29629443/",
    },
    brandBindings: ["brand.businessName", "brand.phone", "brand.logo", "brand.primaryColor", "brand.accentColor"],
    eventIds: ["diwali", "festive-sale-season"],
    elementsFactory: createFestivalGreetingCelebrationElements,
  },
  {
    id: "service-business-promo-01",
    title: "Service Business Promotion",
    category: "Service",
    templateType: "editable",
    format: "square-post",
    thumbnail: "service-business-promo-01.svg",
    primaryImage: "service-business-promo-01-photo.jpg",
    canvas: squareCanvas,
    businessCategories: ["services", "electrical", "general"],
    discoveryTabs: ["for-you", "business"],
    sections: ["recommended-business", "service-promotions", "business-tips", "quick-promotions"],
    tags: ["service", "repair", "booking", "maintenance", "promotion", "local"],
    assets: {
      primaryImageSource: "pexels",
      primaryImageCredit: "Khải Nguyễn Thanh",
      primaryImageUrl: "https://www.pexels.com/photo/chainsaw-repair-workshop-in-phu-yen-vietnam-30199751/",
    },
    brandBindings: ["brand.businessName", "brand.phone", "brand.website", "brand.logo", "brand.primaryColor"],
    elementsFactory: createServiceBusinessPromoElements,
  },
  {
    id: "product-launch-new-arrival-01",
    title: "Product Launch New Arrival",
    category: "Product",
    templateType: "editable",
    format: "square-post",
    thumbnail: "product-launch-new-arrival-01.svg",
    primaryImage: "product-launch-new-arrival-01-photo.jpg",
    canvas: squareCanvas,
    businessCategories: ["general", "clothes", "fashion", "retail"],
    discoveryTabs: ["for-you", "product", "business"],
    sections: ["new-launch", "product-showcase", "trending-designs"],
    tags: ["product", "launch", "new arrival", "showcase", "premium", "retail"],
    assets: {
      primaryImageSource: "pexels",
      primaryImageCredit: "Pușcaș Adryan",
      primaryImageUrl: "https://www.pexels.com/photo/minimalist-face-cream-product-display-in-studio-36339062/",
    },
    brandBindings: ["brand.businessName", "brand.website", "brand.logo", "brand.accentColor"],
    elementsFactory: createProductLaunchNewArrivalElements,
  },
  {
    id: "customer-review-trust-01",
    title: "Customer Review Trust Poster",
    category: "Reviews",
    templateType: "editable",
    format: "square-post",
    thumbnail: "customer-review-trust-01.svg",
    primaryImage: "customer-review-trust-01-photo.jpg",
    canvas: squareCanvas,
    businessCategories: ["general", "services", "restaurant", "clothes"],
    discoveryTabs: ["for-you", "business"],
    sections: ["customer-reviews", "recommended-business", "business-tips"],
    tags: ["review", "testimonial", "trust", "customer", "business", "service"],
    assets: {
      primaryImageSource: "pexels",
      primaryImageCredit: "Craig Adderley",
      primaryImageUrl: "https://www.pexels.com/photo/man-laughing-while-sitting-on-office-chair-1546912/",
    },
    brandBindings: ["brand.businessName", "brand.phone", "brand.logo", "brand.primaryColor"],
    elementsFactory: createCustomerReviewTrustElements,
  },
  {
    id: "business-discount-offer-01",
    title: "Business Discount Offer",
    category: "Business",
    templateType: "editable",
    format: "square-post",
    thumbnail: "business-discount-offer-01.svg",
    primaryImage: "business-discount-offer-01-photo.jpg",
    canvas: squareCanvas,
    businessCategories: ["general", "clothes", "restaurant", "services", "retail"],
    discoveryTabs: ["for-you", "business", "product"],
    sections: ["recommended-business", "quick-promotions", "sale-discount", "service-promotions"],
    tags: ["business", "discount", "offer", "sale", "promotion", "retail"],
    assets: {
      primaryImageSource: "pexels",
      primaryImageCredit: "Farhad Ibrahimzade",
      primaryImageUrl: "https://www.pexels.com/photo/city-fashion-hand-shirt-8743972/",
    },
    brandBindings: ["brand.businessName", "brand.phone", "brand.website", "brand.logo", "brand.accentColor"],
    elementsFactory: createBusinessDiscountOfferElements,
  },
  {
    id: "business-offer-01",
    title: "Weekend Business Offer",
    category: "Business",
    templateType: "editable",
    format: "square-post",
    thumbnail: "business-offer-01.svg",
    canvas: squareCanvas,
    businessCategories: ["general", "clothes", "restaurant", "services"],
    discoveryTabs: ["for-you", "business", "product"],
    sections: ["recommended-business", "trending-designs", "quick-promotions", "service-promotions", "sale-discount"],
    tags: ["business", "offer", "sale", "retail", "service", "local", "quick promotion"],
    brandBindings: ["brand.businessName", "brand.phone", "brand.email", "brand.website", "brand.address", "brand.logo", "brand.primaryColor", "brand.accentColor"],
    eventIds: ["festive-sale-season"],
  },
  {
    id: "product-promo-01",
    title: "Product Launch Promotion",
    category: "Product",
    templateType: "editable",
    format: "square-post",
    thumbnail: "product-promo-01.svg",
    canvas: squareCanvas,
    businessCategories: ["general", "clothes", "retail"],
    discoveryTabs: ["for-you", "product", "business"],
    sections: ["trending-designs", "new-launch", "product-showcase", "quick-promotions"],
    tags: ["product", "launch", "showcase", "new arrival", "retail", "fashion"],
    brandBindings: ["brand.logo", "brand.businessName"],
    eventIds: ["festive-sale-season"],
  },
  {
    id: "info-safety-01",
    title: "Helpful Safety Information Post",
    category: "Helpful",
    templateType: "flat",
    format: "square-post",
    thumbnail: "info-safety-01.svg",
    canvas: squareCanvas,
    businessCategories: ["electrical", "services", "general"],
    discoveryTabs: ["for-you", "business"],
    sections: ["recommended-business", "business-tips", "trending-designs"],
    tags: ["helpful", "tips", "safety", "how-to", "awareness", "electrical", "service"],
    brandBindings: ["brand.logo"],
    eventIds: ["teachers-day", "customer-service-week"],
  },
  {
    id: "quick-personalize-test-01",
    title: "Quick Personalize Festival Poster",
    category: "Festival",
    templateType: "flat",
    format: "square-post",
    thumbnail: "quick-personalize-test-01.svg",
    canvas: squareCanvas,
    businessCategories: ["general", "clothes", "restaurant", "services"],
    discoveryTabs: ["for-you", "festivals", "business"],
    sections: ["quick-promotions", "festival-offers", "greetings"],
    tags: ["quick personalize", "flat", "festival", "poster", "business logo", "heading"],
    brandBindings: ["brand.logo", "brand.businessName"],
    eventIds: ["festive-sale-season"],
    quickPersonalize: {
      headingDefault: "Ganesh Chaturthi Special",
      fields: {
        logo: {
          x: 78,
          y: 76,
          width: 132,
          height: 132,
          cornerRadius: 24,
          borderColor: "#ffffff",
          borderWidth: 5,
          strokeWidth: 5,
        },
        businessName: {
          x: 232,
          y: 96,
          width: 470,
          height: 66,
          fontFamily: "Inter",
          fontSize: 38,
          fontWeight: 900,
          fill: "#ffffff",
          align: "left",
        },
        heading: {
          x: 120,
          y: 744,
          width: 840,
          height: 130,
          fontFamily: "Georgia",
          fontSize: 68,
          fontWeight: 700,
          fill: "#ffffff",
          align: "center",
          lineHeight: 1.05,
        },
      },
    },
  },
  {
    id: "festival-sept14-01",
    title: "Ganesh Chaturthi Orange Poster",
    category: "Festival",
    templateType: "flat",
    format: "portrait-post",
    thumbnail: ganeshPosterOrangeJoyful,
    canvas: ganeshPosterCanvas01,
    businessCategories: ["general", "clothes", "restaurant", "services"],
    discoveryTabs: ["festivals", "for-you", "business"],
    sections: ["upcoming-festivals", "festival-offers", "greetings"],
    tags: ["ganesh chaturthi", "ganesh", "festival", "greeting", "poster", "quick personalize"],
    brandBindings: ["brand.logo", "brand.businessName"],
    eventId: "ganesh-chaturthi",
    eventIds: ["ganesh-chaturthi"],
    quickPersonalize: createGaneshQuickPersonalizeConfig(ganeshPosterCanvas01, "Ganesh Chaturthi Special"),
  },
  {
    id: "festival-sept14-02",
    title: "Ganesh Chaturthi Red Minimal Poster",
    category: "Festival",
    templateType: "flat",
    format: "portrait-post",
    thumbnail: ganeshPosterRedMinimal,
    canvas: ganeshPosterCanvas02,
    businessCategories: ["general", "clothes", "restaurant", "services"],
    discoveryTabs: ["festivals", "for-you", "business"],
    sections: ["upcoming-festivals", "festival-offers", "greetings"],
    tags: ["ganesh chaturthi", "ganesh", "festival", "greeting", "poster", "quick personalize"],
    brandBindings: ["brand.logo", "brand.businessName"],
    eventId: "ganesh-chaturthi",
    eventIds: ["ganesh-chaturthi"],
    quickPersonalize: createGaneshQuickPersonalizeConfig(ganeshPosterCanvas02, "Ganesh Chaturthi Special"),
  },
  {
    id: "festival-sept14-03",
    title: "Ganesh Chaturthi Joyful Flyer",
    category: "Festival",
    templateType: "flat",
    format: "portrait-post",
    thumbnail: ganeshPosterJoyfulFlyer,
    canvas: ganeshPosterCanvas03,
    businessCategories: ["general", "clothes", "restaurant", "services"],
    discoveryTabs: ["festivals", "for-you", "business"],
    sections: ["upcoming-festivals", "festival-offers", "greetings"],
    tags: ["ganesh chaturthi", "ganesh", "festival", "greeting", "flyer", "quick personalize"],
    brandBindings: ["brand.logo", "brand.businessName"],
    eventId: "ganesh-chaturthi",
    eventIds: ["ganesh-chaturthi"],
    quickPersonalize: createGaneshQuickPersonalizeConfig(ganeshPosterCanvas03, "Ganesh Chaturthi Special"),
  },
  {
    id: "festival-ganesh-01",
    title: "Ganesh Festival Greeting",
    category: "Festival",
    templateType: "editable",
    format: "square-post",
    thumbnail: "festival-ganesh-01.svg",
    canvas: squareCanvas,
    businessCategories: ["general", "clothes", "restaurant", "services"],
    discoveryTabs: ["festivals", "for-you"],
    sections: ["upcoming-festivals", "greetings", "festival-offers"],
    tags: ["festival", "greeting", "ganesh", "seasonal", "india"],
    brandBindings: ["brand.businessName", "brand.logo", "brand.primaryColor"],
    eventId: "ganesh-chaturthi",
    eventIds: ["ganesh-chaturthi"],
  },
  {
    id: "fashion-wedding-offer-01",
    title: "Bridal Lehenga Offer",
    category: "Fashion",
    templateType: "flat",
    format: "landscape-post",
    thumbnail: "fashion-wedding-offer-01.svg",
    canvas: landscapeCanvas,
    businessCategories: ["clothes", "fashion", "wedding", "retail"],
    discoveryTabs: ["for-you", "business", "product"],
    sections: ["recommended-business", "trending-designs", "sale-discount", "product-showcase"],
    tags: ["clothes", "fashion", "wedding", "lehenga", "ethnic", "offer"],
    brandBindings: ["brand.businessName", "brand.phone", "brand.logo"],
  },
  {
    id: "ethnic-wear-showcase-01",
    title: "Ethnic Wear Showcase",
    category: "Fashion",
    templateType: "editable",
    format: "landscape-post",
    thumbnail: "ethnic-wear-showcase-01.svg",
    canvas: landscapeCanvas,
    businessCategories: ["clothes", "fashion", "wedding", "retail"],
    discoveryTabs: ["for-you", "business", "product"],
    sections: ["recommended-business", "product-showcase", "trending-designs"],
    tags: ["ethnic", "clothes", "fashion", "showcase", "wedding", "collection"],
    brandBindings: ["brand.businessName", "brand.website", "brand.logo"],
  },
  {
    id: "boutique-sale-01",
    title: "Boutique Festive Sale",
    category: "Fashion",
    templateType: "editable",
    format: "square-post",
    thumbnail: "boutique-sale-01.svg",
    canvas: squareCanvas,
    businessCategories: ["clothes", "fashion", "retail"],
    discoveryTabs: ["for-you", "business", "product"],
    sections: ["recommended-business", "quick-promotions", "sale-discount"],
    tags: ["boutique", "clothes", "fashion", "sale", "offer", "festival"],
    brandBindings: ["brand.businessName", "brand.phone", "brand.accentColor"],
  },
  {
    id: "festive-clothing-offer-01",
    title: "Festive Clothing Offer",
    category: "Fashion",
    templateType: "flat",
    format: "landscape-post",
    thumbnail: "festive-clothing-offer-01.svg",
    canvas: landscapeCanvas,
    businessCategories: ["clothes", "fashion", "retail"],
    discoveryTabs: ["festivals", "business", "product"],
    sections: ["festival-offers", "sale-discount", "quick-promotions"],
    tags: ["festival", "clothes", "fashion", "offer", "sale"],
    brandBindings: ["brand.businessName", "brand.phone", "brand.logo"],
    eventIds: ["festive-sale-season", "diwali"],
  },
  {
    id: "restaurant-menu-offer-01",
    title: "Restaurant Menu Combo",
    category: "Food",
    templateType: "editable",
    format: "square-post",
    thumbnail: "restaurant-menu-offer-01.svg",
    canvas: squareCanvas,
    businessCategories: ["restaurant", "food", "cafe"],
    discoveryTabs: ["for-you", "business", "product"],
    sections: ["recommended-business", "quick-promotions", "service-promotions"],
    tags: ["restaurant", "food", "menu", "combo", "offer", "delivery"],
    brandBindings: ["brand.businessName", "brand.phone", "brand.logo", "brand.accentColor"],
  },
  {
    id: "food-delivery-post-01",
    title: "Fast Delivery Food Promo",
    category: "Food",
    templateType: "flat",
    format: "landscape-post",
    thumbnail: "food-delivery-post-01.svg",
    canvas: landscapeCanvas,
    businessCategories: ["restaurant", "food", "cafe"],
    discoveryTabs: ["business", "product", "for-you"],
    sections: ["quick-promotions", "service-promotions", "sale-discount"],
    tags: ["food", "delivery", "restaurant", "offer", "local"],
    brandBindings: ["brand.businessName", "brand.phone", "brand.website"],
  },
  {
    id: "cafe-review-01",
    title: "Cafe Customer Review",
    category: "Reviews",
    templateType: "editable",
    format: "square-post",
    thumbnail: "cafe-review-01.svg",
    canvas: squareCanvas,
    businessCategories: ["restaurant", "food", "cafe", "services"],
    discoveryTabs: ["business", "for-you"],
    sections: ["customer-reviews", "recommended-business"],
    tags: ["cafe", "review", "customer", "trust", "restaurant"],
    brandBindings: ["brand.businessName", "brand.logo"],
  },
  {
    id: "electrical-service-promo-01",
    title: "Electrical Service Promotion",
    category: "Service",
    templateType: "editable",
    format: "square-post",
    thumbnail: "electrical-service-promo-01.svg",
    canvas: squareCanvas,
    businessCategories: ["electrical", "services"],
    discoveryTabs: ["business", "for-you"],
    sections: ["service-promotions", "business-tips", "recommended-business"],
    tags: ["electrical", "service", "maintenance", "repair", "booking"],
    brandBindings: ["brand.businessName", "brand.phone", "brand.logo"],
  },
  {
    id: "home-maintenance-tip-01",
    title: "Home Maintenance Tips",
    category: "Helpful",
    templateType: "flat",
    format: "square-post",
    thumbnail: "home-maintenance-tip-01.svg",
    canvas: squareCanvas,
    businessCategories: ["electrical", "services", "general"],
    discoveryTabs: ["business", "for-you"],
    sections: ["business-tips", "trending-designs"],
    tags: ["maintenance", "tips", "service", "home", "electrical"],
    brandBindings: ["brand.logo", "brand.website"],
  },
  {
    id: "customer-review-01",
    title: "Happy Customer Review",
    category: "Reviews",
    templateType: "editable",
    format: "square-post",
    thumbnail: "customer-review-01.svg",
    canvas: squareCanvas,
    businessCategories: ["general", "services", "restaurant", "clothes"],
    discoveryTabs: ["business", "product", "for-you"],
    sections: ["customer-reviews", "product-showcase", "trending-designs"],
    tags: ["review", "customer", "trust", "testimonial", "business"],
    brandBindings: ["brand.businessName", "brand.logo", "brand.primaryColor"],
  },
  {
    id: "service-promo-01",
    title: "Book Today Service Promo",
    category: "Service",
    templateType: "editable",
    format: "landscape-post",
    thumbnail: "service-promo-01.svg",
    canvas: landscapeCanvas,
    businessCategories: ["services", "electrical", "general"],
    discoveryTabs: ["business", "for-you"],
    sections: ["service-promotions", "quick-promotions"],
    tags: ["service", "booking", "promotion", "local", "business"],
    brandBindings: ["brand.businessName", "brand.phone", "brand.website"],
  },
  {
    id: "independence-greeting-01",
    title: "Independence Day Greeting",
    category: "Festival",
    templateType: "flat",
    format: "square-post",
    thumbnail: "independence-greeting-01.svg",
    canvas: squareCanvas,
    businessCategories: ["general", "clothes", "restaurant", "services"],
    discoveryTabs: ["festivals", "for-you"],
    sections: ["upcoming-festivals", "greetings"],
    tags: ["independence day", "national", "festival", "greeting", "india"],
    brandBindings: ["brand.businessName", "brand.logo"],
    eventId: "independence-day",
    eventIds: ["independence-day"],
  },
  {
    id: "diwali-sale-01",
    title: "Diwali Sale Creative",
    category: "Festival",
    templateType: "editable",
    format: "square-post",
    thumbnail: "diwali-sale-01.svg",
    canvas: squareCanvas,
    businessCategories: ["general", "clothes", "restaurant", "retail"],
    discoveryTabs: ["festivals", "product", "for-you"],
    sections: ["festival-offers", "sale-discount", "quick-promotions"],
    tags: ["diwali", "festival", "sale", "discount", "offer"],
    brandBindings: ["brand.businessName", "brand.phone", "brand.logo", "brand.accentColor"],
    eventIds: ["diwali", "festive-sale-season"],
  },
  {
    id: "rakhi-greeting-01",
    title: "Rakhi Greeting Post",
    category: "Festival",
    templateType: "flat",
    format: "square-post",
    thumbnail: "rakhi-greeting-01.svg",
    canvas: squareCanvas,
    businessCategories: ["general", "clothes", "retail"],
    discoveryTabs: ["festivals"],
    sections: ["upcoming-festivals", "greetings"],
    tags: ["rakhi", "festival", "greeting", "seasonal"],
    brandBindings: ["brand.businessName", "brand.logo"],
    eventIds: ["rakhi"],
  },
  {
    id: "new-launch-clean-01",
    title: "Clean Product Launch",
    category: "Product",
    templateType: "editable",
    format: "landscape-post",
    thumbnail: "new-launch-clean-01.svg",
    canvas: landscapeCanvas,
    businessCategories: ["general", "clothes", "restaurant", "retail"],
    discoveryTabs: ["product", "for-you"],
    sections: ["new-launch", "trending-designs"],
    tags: ["launch", "new", "product", "announcement"],
    brandBindings: ["brand.businessName", "brand.website", "brand.logo"],
  },
  {
    id: "discount-banner-01",
    title: "Flat Discount Banner",
    category: "Product",
    templateType: "flat",
    format: "landscape-post",
    thumbnail: "discount-banner-01.svg",
    canvas: landscapeCanvas,
    businessCategories: ["general", "clothes", "restaurant", "retail"],
    discoveryTabs: ["product", "business", "for-you"],
    sections: ["sale-discount", "quick-promotions", "festival-offers"],
    tags: ["discount", "sale", "offer", "product", "promotion"],
    brandBindings: ["brand.businessName", "brand.phone", "brand.logo"],
  },
  {
    id: "product-showcase-grid-01",
    title: "Product Showcase Grid",
    category: "Product",
    templateType: "editable",
    format: "square-post",
    thumbnail: "product-showcase-grid-01.svg",
    canvas: squareCanvas,
    businessCategories: ["general", "clothes", "retail"],
    discoveryTabs: ["product"],
    sections: ["product-showcase", "new-launch"],
    tags: ["showcase", "grid", "product", "bundle", "collection"],
    brandBindings: ["brand.businessName", "brand.logo", "brand.primaryColor"],
  },
  {
    id: "beauty-service-offer-01",
    title: "Beauty Service Offer",
    category: "Service",
    templateType: "editable",
    format: "square-post",
    thumbnail: "beauty-service-offer-01.svg",
    canvas: squareCanvas,
    businessCategories: ["services", "general"],
    discoveryTabs: ["business", "for-you"],
    sections: ["service-promotions", "quick-promotions"],
    tags: ["beauty", "salon", "service", "offer", "booking"],
    brandBindings: ["brand.businessName", "brand.phone", "brand.logo"],
  },
  {
    id: "clinic-awareness-01",
    title: "Care Reminder Awareness",
    category: "Helpful",
    templateType: "flat",
    format: "square-post",
    thumbnail: "clinic-awareness-01.svg",
    canvas: squareCanvas,
    businessCategories: ["services", "general"],
    discoveryTabs: ["business", "for-you"],
    sections: ["business-tips", "recommended-business"],
    tags: ["clinic", "health", "care", "awareness", "tips"],
    brandBindings: ["brand.businessName", "brand.phone"],
    eventIds: ["customer-service-week"],
  },
  {
    id: "monsoon-seasonal-offer-01",
    title: "Monsoon Seasonal Deal",
    category: "Seasonal",
    templateType: "flat",
    format: "square-post",
    thumbnail: "monsoon-seasonal-offer-01.svg",
    canvas: squareCanvas,
    businessCategories: ["general", "restaurant", "services", "clothes"],
    discoveryTabs: ["for-you", "business"],
    sections: ["trending-designs", "quick-promotions"],
    tags: ["monsoon", "seasonal", "offer", "sale", "campaign"],
    brandBindings: ["brand.businessName", "brand.website", "brand.logo"],
  },
];

function toTitleCase(value) {
  return String(value || "")
    .replace(/[-_]/g, " ")
    .replace(/\s+/g, " ")
    .trim()
    .replace(/\b\w/g, (letter) => letter.toUpperCase());
}

function getThumbnailPath(fileName) {
  if (!fileName) return "";
  if (/^(https?:|data:|blob:|\/)/.test(fileName)) return fileName;
  return `${ASSET_BASE}/${fileName}`;
}

function createTextElement(id, role, text, overrides = {}) {
  return {
    ...baseElement,
    id,
    type: "text",
    role,
    text,
    x: 120,
    y: 180,
    width: 840,
    height: 90,
    fontFamily: "Inter",
    fontSize: 58,
    fontWeight: 800,
    fontStyle: "normal",
    textDecoration: "",
    fill: "#0f172a",
    align: "center",
    ...overrides,
  };
}

function createImageElement(id, role, src, overrides = {}) {
  return {
    ...baseElement,
    id,
    type: "image",
    role,
    src,
    x: 120,
    y: 120,
    width: 320,
    height: 220,
    flipX: false,
    flipY: false,
    fit: "cover",
    cropX: 0.5,
    cropY: 0.5,
    borderColor: "#ffffff",
    borderWidth: 0,
    strokeWidth: 0,
    cornerRadius: 18,
    ...overrides,
  };
}

function createShapeElement(id, role, overrides = {}) {
  return {
    ...baseElement,
    id,
    type: "shape",
    role,
    shapeType: "rect",
    x: 0,
    y: 0,
    width: 100,
    height: 100,
    fill: "#ffffff",
    stroke: "transparent",
    strokeWidth: 0,
    borderWidth: 0,
    cornerRadius: 0,
    ...overrides,
  };
}

function createFlatBrandOverlays(record) {
  const width = record.canvas.width;
  const height = record.canvas.height;
  const isLandscape = width > height;
  const logoSize = isLandscape ? 92 : 120;

  return [
    createImageElement("brand-logo-overlay", "businessLogo", "", {
      binding: "brand.logo",
      x: isLandscape ? width - 140 : width - 170,
      y: 52,
      width: logoSize,
      height: logoSize,
      borderWidth: 5,
      strokeWidth: 5,
      cornerRadius: 20,
    }),
    createTextElement("brand-name-overlay", "businessName", "Your Business Name", {
      binding: "brand.businessName",
      x: 80,
      y: height - 120,
      width: isLandscape ? 520 : 680,
      height: 46,
      fontSize: isLandscape ? 24 : 30,
      fontWeight: 800,
      fill: "#ffffff",
      align: "left",
    }),
    createTextElement("brand-phone-overlay", "businessPhone", "+91 90000 00000", {
      binding: "brand.phone",
      x: 80,
      y: height - 72,
      width: 360,
      height: 34,
      fontSize: isLandscape ? 18 : 22,
      fontWeight: 700,
      fill: "#ffffff",
      align: "left",
    }),
  ];
}

function createQuickPersonalizeOverlays(record) {
  const fields = record.quickPersonalize?.fields || {};

  return [
    createImageElement("quick-business-logo", "businessLogo", "", {
      binding: "brand.logo",
      quickPersonalizeField: "logo",
      x: 72,
      y: 72,
      width: 128,
      height: 128,
      fit: "contain",
      borderWidth: 4,
      strokeWidth: 4,
      cornerRadius: 22,
      ...(fields.logo || {}),
    }),
    createTextElement("quick-business-name", "businessName", "Your Business Name", {
      binding: "brand.businessName",
      quickPersonalizeField: "businessName",
      x: 220,
      y: 92,
      width: 520,
      height: 60,
      fontSize: 34,
      fontWeight: 900,
      fill: "#ffffff",
      align: "left",
      ...(fields.businessName || {}),
    }),
    createTextElement("quick-custom-heading", "customHeading", record.quickPersonalize?.headingDefault || "Add your heading", {
      quickPersonalizeField: "heading",
      x: 120,
      y: record.canvas.height - 320,
      width: record.canvas.width - 240,
      height: 130,
      fontFamily: "Georgia",
      fontSize: 64,
      fontWeight: 700,
      fill: "#ffffff",
      align: "center",
      ...(fields.heading || {}),
    }),
  ];
}

function createEditableElements(record) {
  const width = record.canvas.width;
  const height = record.canvas.height;
  const isLandscape = width > height;
  const panelX = Math.round(width * 0.08);
  const panelY = Math.round(height * 0.12);
  const panelWidth = Math.round(width * 0.84);
  const panelHeight = Math.round(height * (isLandscape ? 0.42 : 0.48));

  return [
    {
      ...baseElement,
      id: "hero-panel",
      type: "shape",
      role: "decorativeShape",
      styleBindings: { fill: "brand.primaryColor" },
      x: panelX,
      y: panelY,
      width: panelWidth,
      height: panelHeight,
      fill: "#1A1F71",
      stroke: "transparent",
      strokeWidth: 0,
      borderWidth: 0,
      cornerRadius: 42,
      locked: true,
      editable: false,
    },
    createTextElement("headline", "headline", record.title.replace(/(Creative|Promotion|Post)$/i, "").trim(), {
      x: panelX + 48,
      y: panelY + Math.round(panelHeight * 0.22),
      width: panelWidth - 96,
      height: isLandscape ? 74 : 102,
      fontSize: isLandscape ? 52 : 66,
      fill: "#ffffff",
    }),
    createTextElement("supporting-copy", "offer", record.category === "Festival" ? "Celebrate with your customers" : "Ready-to-share business creative", {
      styleBindings: { fill: "brand.accentColor" },
      x: panelX + 72,
      y: panelY + Math.round(panelHeight * 0.58),
      width: panelWidth - 144,
      height: 60,
      fontSize: isLandscape ? 26 : 34,
      fontWeight: 700,
      fill: "#f97316",
    }),
    createImageElement("business-logo", "businessLogo", "", {
      binding: "brand.logo",
      x: Math.round(width / 2 - 70),
      y: isLandscape ? height - 168 : height - 312,
      width: 140,
      height: 110,
      borderColor: "#e2e8f0",
      borderWidth: 4,
      strokeWidth: 4,
      cornerRadius: 18,
    }),
    createTextElement("business-name", "businessName", "Your Business Name", {
      binding: "brand.businessName",
      x: Math.round(width * 0.16),
      y: isLandscape ? height - 86 : height - 178,
      width: Math.round(width * 0.68),
      height: 48,
      fontSize: isLandscape ? 26 : 34,
      fontWeight: 800,
      fill: "#1e3a8a",
    }),
    createTextElement("business-phone", "businessPhone", "+91 90000 00000", {
      binding: "brand.phone",
      x: Math.round(width * 0.2),
      y: isLandscape ? height - 48 : height - 114,
      width: Math.round(width * 0.6),
      height: 34,
      fontSize: isLandscape ? 18 : 24,
      fontWeight: 700,
      fill: "#475569",
    }),
    ...(record.brandBindings.includes("brand.website")
      ? [
          createTextElement("business-website", "businessWebsite", "www.mycompany.com", {
            binding: "brand.website",
            x: Math.round(width * 0.2),
            y: height - 66,
            width: Math.round(width * 0.6),
            height: 32,
            fontSize: isLandscape ? 16 : 22,
            fontWeight: 600,
            fill: "#64748b",
          }),
        ]
      : []),
  ];
}

function createFashionPremiumSaleElements(record) {
  const mainImage = getThumbnailPath(record.primaryImage);

  return [
    {
      ...baseElement,
      id: "poster-background",
      type: "shape",
      role: "background",
      x: 0,
      y: 0,
      width: 1080,
      height: 1080,
      fill: "#f7f1e8",
      stroke: "transparent",
      strokeWidth: 0,
      borderWidth: 0,
      cornerRadius: 0,
      locked: true,
      editable: false,
    },
    createImageElement("fashion-hero-image", "mainImage", mainImage, {
      x: 474,
      y: 0,
      width: 606,
      height: 1080,
      fit: "cover",
      cropX: 0.48,
      cropY: 0.48,
      cornerRadius: 0,
    }),
    {
      ...baseElement,
      id: "copy-panel",
      type: "shape",
      role: "decorativePanel",
      x: 0,
      y: 0,
      width: 560,
      height: 1080,
      fill: "#fbf6ee",
      stroke: "transparent",
      strokeWidth: 0,
      borderWidth: 0,
      cornerRadius: 0,
      locked: true,
      editable: false,
    },
    {
      ...baseElement,
      id: "warm-side-band",
      type: "shape",
      role: "decorativeShape",
      x: 44,
      y: 68,
      width: 12,
      height: 748,
      styleBindings: { fill: "brand.accentColor" },
      fill: "#c7834c",
      stroke: "transparent",
      strokeWidth: 0,
      borderWidth: 0,
      cornerRadius: 999,
      locked: true,
      editable: false,
    },
    createImageElement("business-logo", "businessLogo", "", {
      binding: "brand.logo",
      x: 90,
      y: 70,
      width: 92,
      height: 92,
      fit: "contain",
      borderColor: "#d8c6af",
      borderWidth: 2,
      strokeWidth: 2,
      cornerRadius: 18,
    }),
    createTextElement("business-name", "businessName", "Your Boutique", {
      binding: "brand.businessName",
      x: 202,
      y: 84,
      width: 300,
      height: 44,
      fontFamily: "Inter",
      fontSize: 28,
      fontWeight: 800,
      fill: "#2a2118",
      align: "left",
    }),
    createTextElement("business-phone", "businessPhone", "+91 90000 00000", {
      binding: "brand.phone",
      x: 202,
      y: 126,
      width: 300,
      height: 28,
      fontFamily: "Inter",
      fontSize: 18,
      fontWeight: 700,
      fill: "#7a6450",
      align: "left",
    }),
    createTextElement("headline", "headline", "End of\nSeason Sale", {
      x: 90,
      y: 238,
      width: 410,
      height: 184,
      fontFamily: "Georgia",
      fontSize: 74,
      fontWeight: 700,
      lineHeight: 0.96,
      fill: "#211812",
      align: "left",
    }),
    createTextElement("subheadline", "subheadline", "Up to 40% Off Selected Styles", {
      x: 92,
      y: 455,
      width: 390,
      height: 88,
      fontFamily: "Inter",
      fontSize: 33,
      fontWeight: 800,
      fill: "#8a5839",
      align: "left",
    }),
    {
      ...baseElement,
      id: "sale-badge",
      type: "shape",
      role: "decorativeBadge",
      x: 92,
      y: 575,
      width: 152,
      height: 152,
      styleBindings: { fill: "brand.primaryColor" },
      fill: "#2a2118",
      stroke: "#d7b98d",
      strokeWidth: 5,
      borderWidth: 5,
      cornerRadius: 999,
      locked: true,
      editable: false,
    },
    createTextElement("sale-badge-copy", "decorativeText", "LIMITED\nTIME", {
      x: 112,
      y: 624,
      width: 112,
      height: 60,
      fontFamily: "Inter",
      fontSize: 22,
      fontWeight: 900,
      lineHeight: 1,
      fill: "#fff8ef",
      align: "center",
      locked: true,
      editable: false,
    }),
    {
      ...baseElement,
      id: "cta-pill",
      type: "shape",
      role: "ctaBackground",
      x: 92,
      y: 778,
      width: 308,
      height: 72,
      styleBindings: { fill: "brand.accentColor" },
      fill: "#c7834c",
      stroke: "transparent",
      strokeWidth: 0,
      borderWidth: 0,
      cornerRadius: 999,
      locked: true,
      editable: false,
    },
    createTextElement("cta", "cta", "Shop the Collection", {
      x: 118,
      y: 793,
      width: 256,
      height: 38,
      fontFamily: "Inter",
      fontSize: 24,
      fontWeight: 900,
      fill: "#ffffff",
      align: "center",
    }),
    createTextElement("business-website", "businessWebsite", "www.mycompany.com", {
      binding: "brand.website",
      x: 92,
      y: 955,
      width: 390,
      height: 34,
      fontFamily: "Inter",
      fontSize: 21,
      fontWeight: 800,
      fill: "#2a2118",
      align: "left",
    }),
  ];
}

function createRestaurantFoodOfferElements(record) {
  const mainImage = getThumbnailPath(record.primaryImage);

  return [
    createImageElement("food-hero-image", "mainImage", mainImage, {
      x: 0,
      y: 0,
      width: 1080,
      height: 1080,
      fit: "cover",
      cropX: 0.48,
      cropY: 0.44,
      cornerRadius: 0,
    }),
    createShapeElement("warm-frame", "decorativeFrame", {
      x: 70,
      y: 72,
      width: 940,
      height: 936,
      fill: "transparent",
      stroke: "#f5c16b",
      strokeWidth: 4,
      borderWidth: 4,
      cornerRadius: 44,
      locked: true,
      editable: false,
    }),
    createShapeElement("menu-card", "decorativePanel", {
      x: 92,
      y: 560,
      width: 896,
      height: 358,
      fill: "#fff6e8",
      opacity: 0.96,
      cornerRadius: 36,
      locked: true,
      editable: false,
    }),
    createImageElement("business-logo", "businessLogo", "", {
      binding: "brand.logo",
      x: 126,
      y: 106,
      width: 84,
      height: 84,
      fit: "contain",
      borderColor: "#fff6e8",
      borderWidth: 2,
      strokeWidth: 2,
      cornerRadius: 18,
    }),
    createTextElement("business-name", "businessName", "Your Restaurant", {
      binding: "brand.businessName",
      x: 232,
      y: 126,
      width: 420,
      height: 42,
      fontSize: 30,
      fontWeight: 900,
      fill: "#fff6e8",
      align: "left",
    }),
    createTextElement("business-phone", "businessPhone", "+91 90000 00000", {
      binding: "brand.phone",
      x: 232,
      y: 172,
      width: 360,
      height: 28,
      fontSize: 20,
      fontWeight: 700,
      fill: "#ffe0a6",
      align: "left",
    }),
    createTextElement("headline", "headline", "Family Feast Offer", {
      x: 126,
      y: 634,
      width: 650,
      height: 82,
      fontFamily: "Georgia",
      fontSize: 78,
      fontWeight: 700,
      fill: "#2b160c",
      align: "left",
    }),
    createTextElement("subheadline", "subheadline", "Flat 25% off on combo meals", {
      x: 128,
      y: 738,
      width: 560,
      height: 42,
      fontSize: 34,
      fontWeight: 800,
      fill: "#8c3f17",
      align: "left",
    }),
    createShapeElement("cta-pill", "ctaBackground", {
      x: 130,
      y: 820,
      width: 270,
      height: 64,
      fill: "#b8461c",
      styleBindings: { fill: "brand.accentColor" },
      cornerRadius: 999,
      locked: true,
      editable: false,
    }),
    createTextElement("cta", "cta", "Order Now", {
      x: 150,
      y: 834,
      width: 230,
      height: 34,
      fontSize: 24,
      fontWeight: 900,
      fill: "#ffffff",
      align: "center",
    }),
    createShapeElement("offer-badge", "decorativeBadge", {
      x: 786,
      y: 598,
      width: 144,
      height: 144,
      fill: "#b8461c",
      styleBindings: { fill: "brand.accentColor" },
      shapeType: "circle",
      cornerRadius: 999,
      locked: true,
      editable: false,
    }),
    createTextElement("offer-badge-text", "decorativeText", "SAVE\n25%", {
      x: 804,
      y: 634,
      width: 108,
      height: 74,
      fontSize: 33,
      fontWeight: 900,
      fill: "#fff6e8",
      align: "center",
      lineHeight: 0.95,
      locked: true,
      editable: false,
    }),
  ];
}

function createFestivalGreetingCelebrationElements(record) {
  const mainImage = getThumbnailPath(record.primaryImage);

  return [
    createImageElement("festival-hero-image", "mainImage", mainImage, {
      x: 0,
      y: 0,
      width: 1080,
      height: 1080,
      fit: "cover",
      cropX: 0.5,
      cropY: 0.48,
      cornerRadius: 0,
    }),
    createShapeElement("midnight-overlay", "decorativeOverlay", {
      x: 0,
      y: 0,
      width: 1080,
      height: 1080,
      fill: "#2b1232",
      opacity: 0.42,
      locked: true,
      editable: false,
    }),
    createShapeElement("brand-footer-card", "decorativePanel", {
      x: 118,
      y: 742,
      width: 844,
      height: 174,
      fill: "#fff7e8",
      opacity: 0.92,
      cornerRadius: 38,
      locked: true,
      editable: false,
    }),
    createTextElement("headline", "headline", "Celebrate", {
      x: 190,
      y: 286,
      width: 700,
      height: 90,
      fontFamily: "Georgia",
      fontSize: 86,
      fontWeight: 700,
      fill: "#fff7e8",
      align: "center",
    }),
    createTextElement("subheadline", "subheadline", "Together", {
      x: 220,
      y: 388,
      width: 640,
      height: 74,
      fontFamily: "Georgia",
      fontSize: 72,
      fontStyle: "italic",
      fill: "#ffd98a",
      align: "center",
    }),
    createTextElement("supporting-copy", "greeting", "Warm wishes from our family to yours", {
      x: 214,
      y: 505,
      width: 652,
      height: 44,
      fontSize: 28,
      fontWeight: 800,
      fill: "#fff7e8",
      align: "center",
    }),
    createShapeElement("cta-pill", "ctaBackground", {
      x: 430,
      y: 578,
      width: 220,
      height: 58,
      fill: "#f97316",
      styleBindings: { fill: "brand.accentColor" },
      cornerRadius: 999,
      locked: true,
      editable: false,
    }),
    createTextElement("cta", "cta", "Festive Greetings", {
      x: 448,
      y: 593,
      width: 184,
      height: 30,
      fontSize: 22,
      fontWeight: 900,
      fill: "#ffffff",
      align: "center",
    }),
    createImageElement("business-logo", "businessLogo", "", {
      binding: "brand.logo",
      x: 154,
      y: 786,
      width: 82,
      height: 82,
      fit: "contain",
      borderColor: "#3a173e",
      borderWidth: 2,
      strokeWidth: 2,
      cornerRadius: 20,
    }),
    createTextElement("business-name", "businessName", "Your Business", {
      binding: "brand.businessName",
      x: 260,
      y: 802,
      width: 430,
      height: 42,
      fontSize: 30,
      fontWeight: 900,
      fill: "#2f1735",
      align: "left",
    }),
    createTextElement("business-phone", "businessPhone", "+91 90000 00000", {
      binding: "brand.phone",
      x: 260,
      y: 850,
      width: 360,
      height: 30,
      fontSize: 20,
      fontWeight: 800,
      fill: "#8c5b24",
      align: "left",
    }),
  ];
}

function createServiceBusinessPromoElements(record) {
  const mainImage = getThumbnailPath(record.primaryImage);

  return [
    createShapeElement("soft-background", "background", {
      x: 0,
      y: 0,
      width: 1080,
      height: 1080,
      fill: "#eaf3f6",
      locked: true,
      editable: false,
    }),
    createImageElement("service-hero-image", "mainImage", mainImage, {
      x: 70,
      y: 92,
      width: 490,
      height: 896,
      fit: "cover",
      cropX: 0.5,
      cropY: 0.5,
      borderColor: "#ffffff",
      borderWidth: 12,
      strokeWidth: 12,
      cornerRadius: 42,
    }),
    createShapeElement("brand-card", "decorativePanel", {
      x: 600,
      y: 116,
      width: 386,
      height: 108,
      fill: "#ffffff",
      cornerRadius: 28,
      locked: true,
      editable: false,
    }),
    createImageElement("business-logo", "businessLogo", "", {
      binding: "brand.logo",
      x: 628,
      y: 142,
      width: 56,
      height: 56,
      fit: "contain",
      borderColor: "#1f6f63",
      borderWidth: 2,
      strokeWidth: 2,
      cornerRadius: 14,
    }),
    createTextElement("business-name", "businessName", "Your Service Co.", {
      binding: "brand.businessName",
      x: 704,
      y: 146,
      width: 260,
      height: 34,
      fontSize: 26,
      fontWeight: 900,
      fill: "#12312e",
      align: "left",
    }),
    createTextElement("business-phone", "businessPhone", "+91 90000 00000", {
      binding: "brand.phone",
      x: 704,
      y: 184,
      width: 260,
      height: 26,
      fontSize: 18,
      fontWeight: 700,
      fill: "#64748b",
      align: "left",
    }),
    createTextElement("headline", "headline", "Reliable Service", {
      x: 604,
      y: 320,
      width: 390,
      height: 78,
      fontFamily: "Georgia",
      fontSize: 72,
      fontWeight: 700,
      fill: "#0f172a",
      align: "left",
    }),
    createTextElement("subheadline", "subheadline", "At Your Doorstep", {
      x: 604,
      y: 404,
      width: 390,
      height: 72,
      fontFamily: "Georgia",
      fontSize: 68,
      fontStyle: "italic",
      fill: "#1f6f63",
      align: "left",
    }),
    createTextElement("supporting-copy", "description", "Repair, maintenance and support for busy homes and businesses.", {
      x: 608,
      y: 500,
      width: 380,
      height: 104,
      fontSize: 28,
      fontWeight: 800,
      fill: "#475569",
      align: "left",
    }),
    createShapeElement("cta-pill", "ctaBackground", {
      x: 608,
      y: 632,
      width: 286,
      height: 72,
      fill: "#1f6f63",
      styleBindings: { fill: "brand.primaryColor" },
      cornerRadius: 999,
      locked: true,
      editable: false,
    }),
    createTextElement("cta", "cta", "Book a Visit", {
      x: 632,
      y: 650,
      width: 238,
      height: 34,
      fontSize: 24,
      fontWeight: 900,
      fill: "#ffffff",
      align: "center",
    }),
    createTextElement("business-website", "businessWebsite", "www.mycompany.com", {
      binding: "brand.website",
      x: 608,
      y: 840,
      width: 370,
      height: 30,
      fontSize: 22,
      fontWeight: 800,
      fill: "#0f172a",
      align: "left",
    }),
  ];
}

function createProductLaunchNewArrivalElements(record) {
  const mainImage = getThumbnailPath(record.primaryImage);

  return [
    createShapeElement("warm-background", "background", {
      x: 0,
      y: 0,
      width: 1080,
      height: 1080,
      fill: "#f6efe6",
      locked: true,
      editable: false,
    }),
    createShapeElement("hero-circle-bg", "decorativeShape", {
      x: 440,
      y: 188,
      width: 580,
      height: 580,
      fill: "#f0d6b6",
      opacity: 0.64,
      shapeType: "circle",
      cornerRadius: 999,
      locked: true,
      editable: false,
    }),
    createImageElement("product-hero-image", "mainImage", mainImage, {
      x: 440,
      y: 158,
      width: 580,
      height: 640,
      fit: "contain",
      cropX: 0.5,
      cropY: 0.5,
      borderColor: "#ffffff",
      borderWidth: 12,
      strokeWidth: 12,
      cornerRadius: 42,
    }),
    createTextElement("eyebrow", "eyebrow", "NEW ARRIVAL", {
      x: 92,
      y: 104,
      width: 320,
      height: 34,
      fontSize: 24,
      fontWeight: 900,
      fill: "#2c221a",
      align: "left",
      locked: true,
      editable: false,
    }),
    createTextElement("headline", "headline", "Glow Serum", {
      x: 90,
      y: 238,
      width: 420,
      height: 90,
      fontFamily: "Georgia",
      fontSize: 82,
      fontWeight: 700,
      fill: "#2c221a",
      align: "left",
    }),
    createTextElement("subheadline", "subheadline", "Fresh product drop for modern self-care routines.", {
      x: 92,
      y: 352,
      width: 360,
      height: 110,
      fontSize: 31,
      fontWeight: 800,
      fill: "#8a5a37",
      align: "left",
    }),
    createShapeElement("cta-pill", "ctaBackground", {
      x: 92,
      y: 486,
      width: 278,
      height: 72,
      fill: "#2c221a",
      styleBindings: { fill: "brand.accentColor" },
      cornerRadius: 999,
      locked: true,
      editable: false,
    }),
    createTextElement("cta", "cta", "Explore Now", {
      x: 112,
      y: 504,
      width: 238,
      height: 34,
      fontSize: 24,
      fontWeight: 900,
      fill: "#fffaf2",
      align: "center",
    }),
    createImageElement("business-logo", "businessLogo", "", {
      binding: "brand.logo",
      x: 92,
      y: 802,
      width: 82,
      height: 82,
      fit: "contain",
      borderColor: "#d8c6af",
      borderWidth: 2,
      strokeWidth: 2,
      cornerRadius: 20,
    }),
    createTextElement("business-name", "businessName", "Your Brand", {
      binding: "brand.businessName",
      x: 196,
      y: 816,
      width: 330,
      height: 38,
      fontSize: 29,
      fontWeight: 900,
      fill: "#2c221a",
      align: "left",
    }),
    createTextElement("business-website", "businessWebsite", "www.mycompany.com", {
      binding: "brand.website",
      x: 196,
      y: 864,
      width: 340,
      height: 28,
      fontSize: 20,
      fontWeight: 800,
      fill: "#8a5a37",
      align: "left",
    }),
  ];
}

function createCustomerReviewTrustElements(record) {
  const mainImage = getThumbnailPath(record.primaryImage);

  return [
    createShapeElement("review-background", "background", {
      x: 0,
      y: 0,
      width: 1080,
      height: 1080,
      fill: "#e8eef8",
      locked: true,
      editable: false,
    }),
    createShapeElement("review-card", "decorativePanel", {
      x: 80,
      y: 114,
      width: 920,
      height: 852,
      fill: "#ffffff",
      cornerRadius: 48,
      locked: true,
      editable: false,
    }),
    createImageElement("customer-photo", "mainImage", mainImage, {
      x: 650,
      y: 160,
      width: 318,
      height: 432,
      fit: "cover",
      cropX: 0.5,
      cropY: 0.42,
      cornerRadius: 40,
    }),
    createImageElement("business-logo", "businessLogo", "", {
      binding: "brand.logo",
      x: 118,
      y: 152,
      width: 84,
      height: 84,
      fit: "contain",
      borderColor: "#1a1f71",
      borderWidth: 2,
      strokeWidth: 2,
      cornerRadius: 20,
    }),
    createTextElement("business-name", "businessName", "Your Business", {
      binding: "brand.businessName",
      x: 226,
      y: 172,
      width: 410,
      height: 42,
      fontSize: 30,
      fontWeight: 900,
      fill: "#0f172a",
      align: "left",
    }),
    createTextElement("subheadline", "subheadline", "Trusted by local customers", {
      x: 226,
      y: 220,
      width: 420,
      height: 32,
      fontSize: 20,
      fontWeight: 700,
      fill: "#64748b",
      align: "left",
    }),
    createTextElement("quote-mark", "decorativeText", "“", {
      x: 126,
      y: 346,
      width: 120,
      height: 96,
      fontFamily: "Georgia",
      fontSize: 126,
      fontWeight: 700,
      fill: "#1a1f71",
      locked: true,
      editable: false,
    }),
    createTextElement("headline", "headline", "Loved the service,\nquality and care.", {
      x: 126,
      y: 450,
      width: 520,
      height: 140,
      fontFamily: "Georgia",
      fontSize: 58,
      fontWeight: 700,
      fill: "#0f172a",
      align: "left",
      lineHeight: 1.05,
    }),
    createTextElement("review-copy", "review", "A polished review post for building trust and confidence.", {
      x: 130,
      y: 650,
      width: 520,
      height: 72,
      fontSize: 28,
      fontWeight: 800,
      fill: "#475569",
      align: "left",
    }),
    createTextElement("stars", "rating", "★★★★★", {
      x: 130,
      y: 742,
      width: 240,
      height: 48,
      fontSize: 40,
      fontWeight: 900,
      fill: "#f59e0b",
      align: "left",
    }),
    createShapeElement("cta-pill", "ctaBackground", {
      x: 130,
      y: 838,
      width: 310,
      height: 62,
      fill: "#1a1f71",
      styleBindings: { fill: "brand.primaryColor" },
      cornerRadius: 999,
      locked: true,
      editable: false,
    }),
    createTextElement("cta", "cta", "Share Your Feedback", {
      x: 152,
      y: 854,
      width: 266,
      height: 30,
      fontSize: 23,
      fontWeight: 900,
      fill: "#ffffff",
      align: "center",
    }),
    createTextElement("business-phone", "businessPhone", "+91 90000 00000", {
      binding: "brand.phone",
      x: 650,
      y: 632,
      width: 300,
      height: 32,
      fontSize: 24,
      fontWeight: 900,
      fill: "#0f172a",
      align: "left",
    }),
  ];
}

function createBusinessDiscountOfferElements(record) {
  const mainImage = getThumbnailPath(record.primaryImage);

  return [
    createImageElement("offer-hero-image", "mainImage", mainImage, {
      x: 0,
      y: 0,
      width: 1080,
      height: 1080,
      fit: "cover",
      cropX: 0.52,
      cropY: 0.5,
      cornerRadius: 0,
    }),
    createShapeElement("dark-copy-panel", "decorativeOverlay", {
      x: 0,
      y: 0,
      width: 600,
      height: 1080,
      fill: "#0b1220",
      opacity: 0.82,
      locked: true,
      editable: false,
    }),
    createShapeElement("outline-frame", "decorativeFrame", {
      x: 86,
      y: 86,
      width: 908,
      height: 908,
      fill: "transparent",
      stroke: "#ffffff",
      strokeWidth: 4,
      borderWidth: 4,
      opacity: 0.5,
      cornerRadius: 52,
      locked: true,
      editable: false,
    }),
    createTextElement("eyebrow", "eyebrow", "LIMITED OFFER", {
      x: 126,
      y: 158,
      width: 330,
      height: 34,
      fontSize: 24,
      fontWeight: 900,
      fill: "#ffffff",
      align: "left",
      locked: true,
      editable: false,
    }),
    createTextElement("headline", "headline", "Save Big\nThis Week", {
      x: 126,
      y: 304,
      width: 420,
      height: 174,
      fontFamily: "Georgia",
      fontSize: 86,
      fontWeight: 700,
      fill: "#ffffff",
      align: "left",
      lineHeight: 0.98,
    }),
    createShapeElement("discount-card", "decorativeBadge", {
      x: 126,
      y: 548,
      width: 250,
      height: 126,
      fill: "#f97316",
      styleBindings: { fill: "brand.accentColor" },
      cornerRadius: 28,
      locked: true,
      editable: false,
    }),
    createTextElement("subheadline", "offer", "30% OFF", {
      x: 148,
      y: 585,
      width: 206,
      height: 52,
      fontSize: 54,
      fontWeight: 900,
      fill: "#ffffff",
      align: "center",
    }),
    createTextElement("supporting-copy", "description", "On selected services and products.", {
      x: 126,
      y: 718,
      width: 410,
      height: 44,
      fontSize: 29,
      fontWeight: 800,
      fill: "#e2e8f0",
      align: "left",
    }),
    createShapeElement("cta-pill", "ctaBackground", {
      x: 126,
      y: 830,
      width: 286,
      height: 70,
      fill: "#ffffff",
      cornerRadius: 999,
      locked: true,
      editable: false,
    }),
    createTextElement("cta", "cta", "Claim Offer", {
      x: 150,
      y: 848,
      width: 238,
      height: 34,
      fontSize: 24,
      fontWeight: 900,
      fill: "#0b1220",
      align: "center",
    }),
    createImageElement("business-logo", "businessLogo", "", {
      binding: "brand.logo",
      x: 126,
      y: 928,
      width: 70,
      height: 70,
      fit: "contain",
      borderColor: "#ffffff",
      borderWidth: 2,
      strokeWidth: 2,
      cornerRadius: 16,
    }),
    createTextElement("business-name", "businessName", "Your Business", {
      binding: "brand.businessName",
      x: 214,
      y: 946,
      width: 310,
      height: 34,
      fontSize: 26,
      fontWeight: 900,
      fill: "#ffffff",
      align: "left",
    }),
    createTextElement("business-phone", "businessPhone", "+91 90000 00000", {
      binding: "brand.phone",
      x: 214,
      y: 982,
      width: 300,
      height: 26,
      fontSize: 18,
      fontWeight: 700,
      fill: "#cbd5e1",
      align: "left",
    }),
    createTextElement("business-website", "businessWebsite", "www.mycompany.com", {
      binding: "brand.website",
      x: 690,
      y: 958,
      width: 300,
      height: 28,
      fontSize: 20,
      fontWeight: 800,
      fill: "#ffffff",
      align: "right",
    }),
  ];
}

function createTemplate(record) {
  const thumbnail = getThumbnailPath(record.thumbnail);
  const primaryImage = record.primaryImage ? getThumbnailPath(record.primaryImage) : undefined;
  const isQuickPersonalize = Boolean(record.quickPersonalize);
  const common = {
    id: record.id,
    title: record.title,
    name: record.title,
    category: record.category,
    type: record.templateType,
    templateType: record.templateType,
    editMode: isQuickPersonalize ? "quick-personalize" : record.templateType === "flat" ? "overlay-ready" : "quick-customize",
    format: record.format,
    width: record.canvas.width,
    height: record.canvas.height,
    canvas: record.canvas,
    thumbnail,
    thumbnailAlt: `${record.title} marketing template preview`,
    businessCategories: record.businessCategories,
    discoveryTabs: record.discoveryTabs,
    sections: record.sections,
    tags: record.tags,
    assets: {
      thumbnail,
      ...(primaryImage ? { primaryImage } : {}),
      ...(record.assets || {}),
      source: "local-starter-pack",
    },
    brandBindings: record.brandBindings,
    quickPersonalize: record.quickPersonalize || null,
    editableConfig: {
      supportsBrandBindings: record.brandBindings.length > 0,
      supportsUserOverlays: true,
      supportsElementEditing: record.templateType === "editable" || isQuickPersonalize,
      supportsPosterEditing: record.templateType !== "flat",
    },
    eventId: record.eventId,
    eventIds: record.eventIds || [],
  };

  if (record.templateType === "flat") {
    return {
      ...common,
      background: {
        type: "image",
        src: thumbnail,
        locked: true,
        editable: false,
      },
      elements: isQuickPersonalize ? createQuickPersonalizeOverlays(record) : createFlatBrandOverlays(record),
    };
  }

  return {
    ...common,
    background: {
      type: "shape",
      fill: record.category === "Festival" ? "#fff7ed" : record.category === "Food" ? "#fff7ed" : "#eff6ff",
      locked: true,
      editable: false,
    },
    elements: record.elementsFactory ? record.elementsFactory(record) : createEditableElements(record),
  };
}

export const marketingTemplateRegistry = Object.fromEntries(templateRecords.map((record) => [record.id, createTemplate(record)]));

export const marketingTemplates = Object.values(marketingTemplateRegistry);

export function getTemplateById(id) {
  return marketingTemplateRegistry[id] || null;
}

function getCategoryScore(template, businessCategory = "general") {
  const targetTokens = categoryWeights[businessCategory] || categoryWeights.general;
  const searchable = [
    template.category,
    template.title,
    template.format,
    ...template.businessCategories,
    ...template.tags,
    ...template.sections,
  ]
    .join(" ")
    .toLowerCase();

  return targetTokens.reduce((score, token) => score + (searchable.includes(token) ? 1 : 0), 0);
}

export function resolveTemplates(templateIds = []) {
  const seen = new Set();
  return templateIds
    .map((id) => getTemplateById(id))
    .filter(Boolean)
    .filter((template) => {
      if (seen.has(template.id)) return false;
      seen.add(template.id);
      return true;
    });
}

export function resolveDiscoveryTemplates(templateIds = [], options = {}) {
  const templates = resolveTemplates(templateIds);
  const businessCategory = options.businessCategory || "general";

  return [...templates].sort((a, b) => {
    const categoryDelta = getCategoryScore(b, businessCategory) - getCategoryScore(a, businessCategory);
    if (categoryDelta !== 0) return categoryDelta;
    return toTitleCase(a.category).localeCompare(toTitleCase(b.category));
  });
}
