export const gstTypes = [
  "Unregistered / Consumer",
  "Registered Business - Regular",
  "Registered Business - Composition",
];

export const indianStates = [
  "Andaman and Nicobar Islands",
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chandigarh",
  "Chhattisgarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Delhi",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jammu and Kashmir",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Ladakh",
  "Lakshadweep",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Puducherry",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
];

export const additionalPartyFields = [
  { id: "field-1", fieldName: "", value: "", showInPrint: false, enabled: false, type: "text" },
  { id: "field-2", fieldName: "", value: "", showInPrint: false, enabled: false, type: "text" },
  { id: "field-3", fieldName: "", value: "", showInPrint: false, enabled: false, type: "text" },
  { id: "field-4", fieldName: "", value: "", showInPrint: false, enabled: false, type: "date" },
];

export const partyFormDefaults = {
  partyName: "",
  gstin: "",
  phone: "",
  gstType: gstTypes[0],
  state: "",
  email: "",
  billingAddress: "",
  shippingAddress: "",
  openingBalance: "",
  asOfDate: "",
  creditLimitType: "no-limit",
  creditLimit: "",
  additionalFields: additionalPartyFields,
};
